/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin/route'
import { Route as IndexImport } from './routes/index'
import { Route as AdminGoogleAdRouteImport } from './routes/admin/googleAd/route'
import { Route as AdminImageLibraryRouteImport } from './routes/admin/ImageLibrary/route'
import { Route as AdminGoogleAdSalerRouteImport } from './routes/admin/googleAd/saler/route'
import { Route as AdminGoogleAdPageRouteImport } from './routes/admin/googleAd/page/route'
import { Route as AdminImageLibraryListNumImport } from './routes/admin/ImageLibrary/list.$num'
import { Route as AdminGoogleAdSalerListPageImport } from './routes/admin/googleAd/saler/list.$page'
import { Route as AdminGoogleAdSalerEditIdImport } from './routes/admin/googleAd/saler/edit.$id'
import { Route as AdminGoogleAdPageListPageImport } from './routes/admin/googleAd/page/list.$page'
import { Route as AdminGoogleAdPageEditIdImport } from './routes/admin/googleAd/page/edit.$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AdminRouteRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminGoogleAdRouteRoute = AdminGoogleAdRouteImport.update({
  id: '/googleAd',
  path: '/googleAd',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminImageLibraryRouteRoute = AdminImageLibraryRouteImport.update({
  id: '/ImageLibrary',
  path: '/ImageLibrary',
  getParentRoute: () => AdminRouteRoute,
} as any)

const AdminGoogleAdSalerRouteRoute = AdminGoogleAdSalerRouteImport.update({
  id: '/saler',
  path: '/saler',
  getParentRoute: () => AdminGoogleAdRouteRoute,
} as any)

const AdminGoogleAdPageRouteRoute = AdminGoogleAdPageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => AdminGoogleAdRouteRoute,
} as any)

const AdminImageLibraryListNumRoute = AdminImageLibraryListNumImport.update({
  id: '/list/$num',
  path: '/list/$num',
  getParentRoute: () => AdminImageLibraryRouteRoute,
} as any)

const AdminGoogleAdSalerListPageRoute = AdminGoogleAdSalerListPageImport.update(
  {
    id: '/list/$page',
    path: '/list/$page',
    getParentRoute: () => AdminGoogleAdSalerRouteRoute,
  } as any,
)

const AdminGoogleAdSalerEditIdRoute = AdminGoogleAdSalerEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminGoogleAdSalerRouteRoute,
} as any)

const AdminGoogleAdPageListPageRoute = AdminGoogleAdPageListPageImport.update({
  id: '/list/$page',
  path: '/list/$page',
  getParentRoute: () => AdminGoogleAdPageRouteRoute,
} as any)

const AdminGoogleAdPageEditIdRoute = AdminGoogleAdPageEditIdImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminGoogleAdPageRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/admin/ImageLibrary': {
      id: '/admin/ImageLibrary'
      path: '/ImageLibrary'
      fullPath: '/admin/ImageLibrary'
      preLoaderRoute: typeof AdminImageLibraryRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/googleAd': {
      id: '/admin/googleAd'
      path: '/googleAd'
      fullPath: '/admin/googleAd'
      preLoaderRoute: typeof AdminGoogleAdRouteImport
      parentRoute: typeof AdminRouteImport
    }
    '/admin/googleAd/page': {
      id: '/admin/googleAd/page'
      path: '/page'
      fullPath: '/admin/googleAd/page'
      preLoaderRoute: typeof AdminGoogleAdPageRouteImport
      parentRoute: typeof AdminGoogleAdRouteImport
    }
    '/admin/googleAd/saler': {
      id: '/admin/googleAd/saler'
      path: '/saler'
      fullPath: '/admin/googleAd/saler'
      preLoaderRoute: typeof AdminGoogleAdSalerRouteImport
      parentRoute: typeof AdminGoogleAdRouteImport
    }
    '/admin/ImageLibrary/list/$num': {
      id: '/admin/ImageLibrary/list/$num'
      path: '/list/$num'
      fullPath: '/admin/ImageLibrary/list/$num'
      preLoaderRoute: typeof AdminImageLibraryListNumImport
      parentRoute: typeof AdminImageLibraryRouteImport
    }
    '/admin/googleAd/page/edit/$id': {
      id: '/admin/googleAd/page/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/googleAd/page/edit/$id'
      preLoaderRoute: typeof AdminGoogleAdPageEditIdImport
      parentRoute: typeof AdminGoogleAdPageRouteImport
    }
    '/admin/googleAd/page/list/$page': {
      id: '/admin/googleAd/page/list/$page'
      path: '/list/$page'
      fullPath: '/admin/googleAd/page/list/$page'
      preLoaderRoute: typeof AdminGoogleAdPageListPageImport
      parentRoute: typeof AdminGoogleAdPageRouteImport
    }
    '/admin/googleAd/saler/edit/$id': {
      id: '/admin/googleAd/saler/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/googleAd/saler/edit/$id'
      preLoaderRoute: typeof AdminGoogleAdSalerEditIdImport
      parentRoute: typeof AdminGoogleAdSalerRouteImport
    }
    '/admin/googleAd/saler/list/$page': {
      id: '/admin/googleAd/saler/list/$page'
      path: '/list/$page'
      fullPath: '/admin/googleAd/saler/list/$page'
      preLoaderRoute: typeof AdminGoogleAdSalerListPageImport
      parentRoute: typeof AdminGoogleAdSalerRouteImport
    }
  }
}

// Create and export the route tree

interface AdminImageLibraryRouteRouteChildren {
  AdminImageLibraryListNumRoute: typeof AdminImageLibraryListNumRoute
}

const AdminImageLibraryRouteRouteChildren: AdminImageLibraryRouteRouteChildren =
  {
    AdminImageLibraryListNumRoute: AdminImageLibraryListNumRoute,
  }

const AdminImageLibraryRouteRouteWithChildren =
  AdminImageLibraryRouteRoute._addFileChildren(
    AdminImageLibraryRouteRouteChildren,
  )

interface AdminGoogleAdPageRouteRouteChildren {
  AdminGoogleAdPageEditIdRoute: typeof AdminGoogleAdPageEditIdRoute
  AdminGoogleAdPageListPageRoute: typeof AdminGoogleAdPageListPageRoute
}

const AdminGoogleAdPageRouteRouteChildren: AdminGoogleAdPageRouteRouteChildren =
  {
    AdminGoogleAdPageEditIdRoute: AdminGoogleAdPageEditIdRoute,
    AdminGoogleAdPageListPageRoute: AdminGoogleAdPageListPageRoute,
  }

const AdminGoogleAdPageRouteRouteWithChildren =
  AdminGoogleAdPageRouteRoute._addFileChildren(
    AdminGoogleAdPageRouteRouteChildren,
  )

interface AdminGoogleAdSalerRouteRouteChildren {
  AdminGoogleAdSalerEditIdRoute: typeof AdminGoogleAdSalerEditIdRoute
  AdminGoogleAdSalerListPageRoute: typeof AdminGoogleAdSalerListPageRoute
}

const AdminGoogleAdSalerRouteRouteChildren: AdminGoogleAdSalerRouteRouteChildren =
  {
    AdminGoogleAdSalerEditIdRoute: AdminGoogleAdSalerEditIdRoute,
    AdminGoogleAdSalerListPageRoute: AdminGoogleAdSalerListPageRoute,
  }

const AdminGoogleAdSalerRouteRouteWithChildren =
  AdminGoogleAdSalerRouteRoute._addFileChildren(
    AdminGoogleAdSalerRouteRouteChildren,
  )

interface AdminGoogleAdRouteRouteChildren {
  AdminGoogleAdPageRouteRoute: typeof AdminGoogleAdPageRouteRouteWithChildren
  AdminGoogleAdSalerRouteRoute: typeof AdminGoogleAdSalerRouteRouteWithChildren
}

const AdminGoogleAdRouteRouteChildren: AdminGoogleAdRouteRouteChildren = {
  AdminGoogleAdPageRouteRoute: AdminGoogleAdPageRouteRouteWithChildren,
  AdminGoogleAdSalerRouteRoute: AdminGoogleAdSalerRouteRouteWithChildren,
}

const AdminGoogleAdRouteRouteWithChildren =
  AdminGoogleAdRouteRoute._addFileChildren(AdminGoogleAdRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminImageLibraryRouteRoute: typeof AdminImageLibraryRouteRouteWithChildren
  AdminGoogleAdRouteRoute: typeof AdminGoogleAdRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminImageLibraryRouteRoute: AdminImageLibraryRouteRouteWithChildren,
  AdminGoogleAdRouteRoute: AdminGoogleAdRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/ImageLibrary': typeof AdminImageLibraryRouteRouteWithChildren
  '/admin/googleAd': typeof AdminGoogleAdRouteRouteWithChildren
  '/admin/googleAd/page': typeof AdminGoogleAdPageRouteRouteWithChildren
  '/admin/googleAd/saler': typeof AdminGoogleAdSalerRouteRouteWithChildren
  '/admin/ImageLibrary/list/$num': typeof AdminImageLibraryListNumRoute
  '/admin/googleAd/page/edit/$id': typeof AdminGoogleAdPageEditIdRoute
  '/admin/googleAd/page/list/$page': typeof AdminGoogleAdPageListPageRoute
  '/admin/googleAd/saler/edit/$id': typeof AdminGoogleAdSalerEditIdRoute
  '/admin/googleAd/saler/list/$page': typeof AdminGoogleAdSalerListPageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/ImageLibrary': typeof AdminImageLibraryRouteRouteWithChildren
  '/admin/googleAd': typeof AdminGoogleAdRouteRouteWithChildren
  '/admin/googleAd/page': typeof AdminGoogleAdPageRouteRouteWithChildren
  '/admin/googleAd/saler': typeof AdminGoogleAdSalerRouteRouteWithChildren
  '/admin/ImageLibrary/list/$num': typeof AdminImageLibraryListNumRoute
  '/admin/googleAd/page/edit/$id': typeof AdminGoogleAdPageEditIdRoute
  '/admin/googleAd/page/list/$page': typeof AdminGoogleAdPageListPageRoute
  '/admin/googleAd/saler/edit/$id': typeof AdminGoogleAdSalerEditIdRoute
  '/admin/googleAd/saler/list/$page': typeof AdminGoogleAdSalerListPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/ImageLibrary': typeof AdminImageLibraryRouteRouteWithChildren
  '/admin/googleAd': typeof AdminGoogleAdRouteRouteWithChildren
  '/admin/googleAd/page': typeof AdminGoogleAdPageRouteRouteWithChildren
  '/admin/googleAd/saler': typeof AdminGoogleAdSalerRouteRouteWithChildren
  '/admin/ImageLibrary/list/$num': typeof AdminImageLibraryListNumRoute
  '/admin/googleAd/page/edit/$id': typeof AdminGoogleAdPageEditIdRoute
  '/admin/googleAd/page/list/$page': typeof AdminGoogleAdPageListPageRoute
  '/admin/googleAd/saler/edit/$id': typeof AdminGoogleAdSalerEditIdRoute
  '/admin/googleAd/saler/list/$page': typeof AdminGoogleAdSalerListPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/ImageLibrary'
    | '/admin/googleAd'
    | '/admin/googleAd/page'
    | '/admin/googleAd/saler'
    | '/admin/ImageLibrary/list/$num'
    | '/admin/googleAd/page/edit/$id'
    | '/admin/googleAd/page/list/$page'
    | '/admin/googleAd/saler/edit/$id'
    | '/admin/googleAd/saler/list/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/ImageLibrary'
    | '/admin/googleAd'
    | '/admin/googleAd/page'
    | '/admin/googleAd/saler'
    | '/admin/ImageLibrary/list/$num'
    | '/admin/googleAd/page/edit/$id'
    | '/admin/googleAd/page/list/$page'
    | '/admin/googleAd/saler/edit/$id'
    | '/admin/googleAd/saler/list/$page'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/ImageLibrary'
    | '/admin/googleAd'
    | '/admin/googleAd/page'
    | '/admin/googleAd/saler'
    | '/admin/ImageLibrary/list/$num'
    | '/admin/googleAd/page/edit/$id'
    | '/admin/googleAd/page/list/$page'
    | '/admin/googleAd/saler/edit/$id'
    | '/admin/googleAd/saler/list/$page'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/admin",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/admin": {
      "filePath": "admin/route.tsx",
      "children": [
        "/admin/ImageLibrary",
        "/admin/googleAd"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/admin/ImageLibrary": {
      "filePath": "admin/ImageLibrary/route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/ImageLibrary/list/$num"
      ]
    },
    "/admin/googleAd": {
      "filePath": "admin/googleAd/route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/googleAd/page",
        "/admin/googleAd/saler"
      ]
    },
    "/admin/googleAd/page": {
      "filePath": "admin/googleAd/page/route.tsx",
      "parent": "/admin/googleAd",
      "children": [
        "/admin/googleAd/page/edit/$id",
        "/admin/googleAd/page/list/$page"
      ]
    },
    "/admin/googleAd/saler": {
      "filePath": "admin/googleAd/saler/route.tsx",
      "parent": "/admin/googleAd",
      "children": [
        "/admin/googleAd/saler/edit/$id",
        "/admin/googleAd/saler/list/$page"
      ]
    },
    "/admin/ImageLibrary/list/$num": {
      "filePath": "admin/ImageLibrary/list.$num.tsx",
      "parent": "/admin/ImageLibrary"
    },
    "/admin/googleAd/page/edit/$id": {
      "filePath": "admin/googleAd/page/edit.$id.tsx",
      "parent": "/admin/googleAd/page"
    },
    "/admin/googleAd/page/list/$page": {
      "filePath": "admin/googleAd/page/list.$page.tsx",
      "parent": "/admin/googleAd/page"
    },
    "/admin/googleAd/saler/edit/$id": {
      "filePath": "admin/googleAd/saler/edit.$id.tsx",
      "parent": "/admin/googleAd/saler"
    },
    "/admin/googleAd/saler/list/$page": {
      "filePath": "admin/googleAd/saler/list.$page.tsx",
      "parent": "/admin/googleAd/saler"
    }
  }
}
ROUTE_MANIFEST_END */
